/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.manufacturer;

import Services.MailService;
import database.InventoryItemService;
import database.ManufacturingRequestsService;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.InventoryItem;
import model.Manufacturer;
import model.ManufacturingRequests;

/**
 *
 * @author madhav
 */
public class ManufacturingWorkflowRequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufacturingWorkflowRequestsPanel
     */
    JSplitPane mainPanel;
    ArrayList<Component> al;
    ManufacturingRequestsService iis;
    Manufacturer ph;
    public ManufacturingWorkflowRequestsPanel(Manufacturer ph, JSplitPane mainPanel, ArrayList<Component> al) {
        initComponents();
        iis = new ManufacturingRequestsService();
        this.mainPanel = mainPanel;
        this.al = al;
        this.ph = ph;
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();
        model.setRowCount(0);
        ArrayList<ManufacturingRequests> reqs = new ArrayList<>();
        if(ph != null) {
            reqs = this.iis.getAllManufacturingRequestssOfManufacturer(ph.getId());
        } 
        for(ManufacturingRequests item: reqs) {
                Object[] row = new Object[3];
                
                System.out.println("Done");
                if(item.getPharmacy()!= null) {
                    row[0] = item.getPharmacy().getName();
                } else {
                    row[0] = "NA";
                }
                row[1] = item;
                row[2] = item.getQty();

                model.addRow(row);
            
        }
//        this.txtDiagnose.setEditable(false);
        this.lblStatus.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounters = new javax.swing.JTable();
        btnLeave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiagnose = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnFullfill = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/back.png"))); // NOI18N
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manufacturering Requests");

        tblEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pharmacy", "Name", "Quantity"
            }
        ));
        tblEncounters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEncountersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEncounters);

        btnLeave.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnLeave.setForeground(new java.awt.Color(255, 0, 0));
        btnLeave.setText("Delete");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        txtDiagnose.setColumns(20);
        txtDiagnose.setRows(5);
        jScrollPane2.setViewportView(txtDiagnose);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Quantity");

        lblStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblStatus.setText("Type");

        btnFullfill.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnFullfill.setText("Fullfill and Complete");
        btnFullfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullfillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack2)
                .addContainerGap(781, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnFullfill)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnLeave))
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnBack2)
                .addContainerGap(523, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStatus)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnFullfill)
                            .addGap(112, 112, 112)
                            .addComponent(btnLeave))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblEncountersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncountersMouseClicked
        // TODO add your handling code here:
        int idx = this.tblEncounters.getSelectedRow();
        if(idx<0) {
            JOptionPane.showMessageDialog(this, "Not correct index");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();

        ManufacturingRequests item = (ManufacturingRequests) model.getValueAt(idx, 1);
        if(item == null) {
            JOptionPane.showMessageDialog(this, "Not correct item");
            return;
        }
        if(item.getInventoryItem().getQty()== 0) {
            this.lblStatus.setText("Out Of Stock");
            
        }
        this.btnFullfill.setEnabled(true);
            this.txtDiagnose.setText(String.valueOf(item.getQty()));
    }//GEN-LAST:event_tblEncountersMouseClicked

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
        int idx = this.tblEncounters.getSelectedRow();
        if(idx<0) {
            JOptionPane.showMessageDialog(this, "Not correct index");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();

        ManufacturingRequests item = (ManufacturingRequests) model.getValueAt(idx, 1);
        if(item == null) {
            JOptionPane.showMessageDialog(this, "Not correct item");
            return;
        }
        iis.deleteManufacturingRequests(item.getId());

        model.setRowCount(0);
        ArrayList<ManufacturingRequests> reqs = new ArrayList<>();

        if(ph != null) {
            reqs = this.iis.getAllManufacturingRequestssOfManufacturer(ph.getId());
        }
        for(ManufacturingRequests it: reqs) {
            Object[] row = new Object[4];

            System.out.println("Done");
            if(item.getPharmacy()!=null) {
                row[0] = item.getPharmacy().getName();
            } else {
                row[0] = "NA";
            }
            row[1] = it;
            row[2] = it.getQty();

            model.addRow(row);

        }
        //        this.txtDiagnose.setEditable(false);
        this.btnFullfill.setEnabled(false);
        this.lblStatus.setText("");

        this.txtDiagnose.setEnabled(false);
        this.txtDiagnose.setText("");
                JOptionPane.showMessageDialog(this, "Deleted");

    }//GEN-LAST:event_btnLeaveActionPerformed

    private void btnFullfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullfillActionPerformed
        // TODO add your handling code here:
        int idx = this.tblEncounters.getSelectedRow();
        if(idx<0) {
            JOptionPane.showMessageDialog(this, "Not correct index");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();

        ManufacturingRequests item = (ManufacturingRequests) model.getValueAt(idx, 1);
        if(item == null) {
            JOptionPane.showMessageDialog(this, "Not correct item");
            return;
        }
        //        String address = item.getManufacturer().getEmail();
        //        MailService es = new MailService();
        //        es.actionPerformed("Out of stock for"+ item.getName(), "Out of stock for"+ item.getName(), item.getPharmacy().getEmail(), address);
        if(this.txtDiagnose.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Not correct qty");
            return;
        }

        int qty = Integer.parseInt(this.txtDiagnose.getText());
        InventoryItem i = item.getInventoryItem();
        i.setQty(i.getQty()+qty);
        
        
        
        InventoryItemService mas = new InventoryItemService();
        String s = mas.update(i);
        JOptionPane.showMessageDialog(this, s);
        
        //delete request
        
         iis.deleteManufacturingRequests(item.getId());
         
        if(item.getPharmacy() != null) {
            String address = item.getPharmacy().getEmail();
            MailService es = new MailService();
            es.actionPerformed("Qty Request updated for "+ item.getName(), "Qty Request updated for "+ item.getName(), "", address);
                
        }
        model.setRowCount(0);
        ArrayList<ManufacturingRequests> reqs = new ArrayList<>();

        if(ph != null) {
            reqs = this.iis.getAllManufacturingRequestssOfManufacturer(ph.getId());
        }
        for(ManufacturingRequests it: reqs) {
            Object[] row = new Object[4];

            System.out.println("Done");
            if(item.getPharmacy()!=null) {
                row[0] = item.getPharmacy().getName();
            } else {
                row[0] = "NA";
            }
            row[1] = it;
            row[2] = it.getQty();

            model.addRow(row);

        }
        
        //        this.txtDiagnose.setEditable(false);
        this.btnFullfill.setEnabled(false);
        this.lblStatus.setText("");

        this.txtDiagnose.setEnabled(false);
        this.txtDiagnose.setText("");
        JOptionPane.showMessageDialog(this, "Fullfilled");
            
    }//GEN-LAST:event_btnFullfillActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        Component c = this.al.get(this.al.size()-1);
        this.al.remove(this.al.size()-1);
        this.mainPanel.setRightComponent(c);
    }//GEN-LAST:event_btnBack2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnFullfill;
    private javax.swing.JButton btnLeave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblEncounters;
    private javax.swing.JTextArea txtDiagnose;
    // End of variables declaration//GEN-END:variables
}
