/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import javax.swing.JOptionPane;
import model.DataService;
import model.Doctor;

/**
 *
 * @author somes
 */
public class CreateDocJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDocJPanel
     */
    DataService doctr;
    public CreateDocJPanel(DataService doctr) {
        initComponents();
        
        this.doctr=doctr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHospID = new javax.swing.JTextField();
        btnSaveDoc = new javax.swing.JButton();
        lblDoc = new javax.swing.JLabel();
        lblDocName = new javax.swing.JLabel();
        lblDocID = new javax.swing.JLabel();
        lblDocHospID = new javax.swing.JLabel();
        txtDocName = new javax.swing.JTextField();
        txtDocID = new javax.swing.JTextField();
        lblDocHospUN = new javax.swing.JLabel();
        txtDocUN = new javax.swing.JTextField();
        lblDocPass = new javax.swing.JLabel();
        txtDocPass = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 255));

        btnSaveDoc.setText("Save");
        btnSaveDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDocActionPerformed(evt);
            }
        });

        lblDoc.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoc.setText("Enter Doctor Details");

        lblDocName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocName.setText("Doctor Name:");

        lblDocID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocID.setText("Doctor ID:");

        lblDocHospID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocHospID.setText("Hospital ID:");

        lblDocHospUN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocHospUN.setText("Doctor Username :");

        lblDocPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocPass.setText("Doctor Password :");

        txtDocPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDocPass)
                    .addComponent(lblDocID)
                    .addComponent(lblDocName)
                    .addComponent(lblDocHospID)
                    .addComponent(lblDocHospUN))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDocName)
                        .addComponent(txtDocID)
                        .addComponent(txtHospID)
                        .addComponent(txtDocUN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocPass, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnSaveDoc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocName)
                    .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocID)
                    .addComponent(txtDocID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHospID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocHospID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocHospUN)
                    .addComponent(txtDocUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocPass)
                    .addComponent(txtDocPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveDoc)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public boolean isEmpty(String c){
        return c != null && c.length() ==0;
        }
    
    
    public boolean isStrongPassword(String s) {  
    return s != null && s.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$");  
    } 
    
    private void btnSaveDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDocActionPerformed
        // TODO add your handling code here:
        if(doctr!=null){
            
            
            if(isEmpty(txtDocName.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter Doctor Name");
            return;
            }
            String docName = txtDocName.getText();
            
            if(isEmpty(txtDocID.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter Doctor ID");
            return;
            }
            String docID = txtDocID.getText();
            
            if(isEmpty(txtHospID.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter Hospital ID");
            return;
            }
            String hospID = txtHospID.getText();
            
             if(isEmpty(txtDocUN.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter Doc Username");
            return;
            }
            String docUN = txtDocUN.getText();
            
             if(!isStrongPassword(txtDocPass.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter Hospital ID Doc Password");
            return;
            }
            String docPass = txtDocPass.getText();
            
            Doctor doc = doctr.addNewDoc();
            
            doc.setDocName(docName);
            doc.setDocID(docID);
            doc.setHospID(hospID);
            doc.setDocUsername(docUN);
            doc.setDocPass(docPass);
            JOptionPane.showMessageDialog(this,"New Doctor Added to List");
    
            txtDocName.setText("");
            txtDocID.setText("");
            txtHospID.setText("");
            txtDocUN.setText("");
            txtHospID.setText("");
            txtDocPass.setText("");
            
        }
        else{
            JOptionPane.showMessageDialog(this,"No Doctor");
        }
    }//GEN-LAST:event_btnSaveDocActionPerformed

    private void txtDocPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDoc;
    private javax.swing.JLabel lblDoc;
    private javax.swing.JLabel lblDocHospID;
    private javax.swing.JLabel lblDocHospUN;
    private javax.swing.JLabel lblDocID;
    private javax.swing.JLabel lblDocName;
    private javax.swing.JLabel lblDocPass;
    private javax.swing.JTextField txtDocID;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtDocPass;
    private javax.swing.JTextField txtDocUN;
    private javax.swing.JTextField txtHospID;
    // End of variables declaration//GEN-END:variables
}
