/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Patient;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.DataService;
import model.Community;
/**
 *
 * @author madhav
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    DataService ds;
     
    public CreatePatientJPanel(DataService ds) {
        initComponents();
        this.ds=ds;
      
        
     }
     
    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @param s
     */
    @SuppressWarnings("unchecked")
    
    public boolean isStrongPassword(String s) {  
    return s != null && s.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$");  
    } 
    
    public boolean isEmpty(String c){
        
        return c != null && c.length() ==0;
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblHouseName = new javax.swing.JLabel();
        lblCommId = new javax.swing.JLabel();
        lblHospId = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPwd = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        txtHouseName = new javax.swing.JTextField();
        txtHospId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtCommId = new javax.swing.JTextField();

        jLabel1.setText("Add Patient Details");

        lblUserName.setText("User Name");

        lblPwd.setText("Password");

        lblPatientName.setText("Patient Name");

        lblPatientId.setText("     Patient Id");

        lblHouseName.setText("HouseName");

        lblCommId.setText("Community ID");

        lblHospId.setText("Hospital ID");

        txtUserName.setText(" ");
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        txtPwd.setText(" ");
        txtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwdActionPerformed(evt);
            }
        });

        txtPatientName.setText(" ");
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtPatientId.setText(" ");

        txtHouseName.setText(" ");

        txtHospId.setText(" ");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPwd)
                            .addComponent(lblUserName)
                            .addComponent(lblPatientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHouseName)
                            .addComponent(lblCommId)
                            .addComponent(lblHospId)
                            .addComponent(lblPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txtPwd)
                            .addComponent(txtPatientName)
                            .addComponent(txtPatientId)
                            .addComponent(txtHouseName)
                            .addComponent(txtHospId)
                            .addComponent(txtCommId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnSave)))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatientId)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHouseName)
                    .addComponent(txtHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCommId)
                    .addComponent(txtCommId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospId)
                    .addComponent(txtHospId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(isEmpty(txtPatientName.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter patient name");
            return;
        } 
        String patientname = txtPatientName.getText().trim();
        if(isEmpty(txtPatientId.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter patient name");
            return;
        } 
        
        String patientid=txtPatientId.getText().trim();
        
        if(isEmpty(txtUserName.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter patient name");
            return;
        } 
        
        String Username = txtUserName.getText().trim();
        if(isEmpty(txtHospId.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter patient name");
            return;
        } 
        String hospid=txtHospId.getText().trim();
        if(isEmpty(txtHouseName.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter patient name");
            return;
        } 
        
        
        String Housename = txtHouseName.getText().trim();
        
        if(isEmpty(txtCommId.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter patient name");
            return;
        } 
        
        
        String communityName = txtCommId.getText().trim();
        
       
        
        
        
        
        if(isEmpty(txtPwd.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter strong password");
            return;
        }
        
        String password= txtPwd.getText().trim();
        
        Patient p= ds.addPatients();
        
        
        p.setCommunityId(communityName);
        p.setHospId(hospid);
        p.setHouseName(Housename);
        p.setPatientName(patientname);
        p.setPatientId(patientid);
        p.setUserName(Username);
        p.setPwd(password);
        
        
        JOptionPane.showMessageDialog(this,"New Patient  Added");
        
        txtPatientName.setText("");
        txtPatientId.setText("");
        txtUserName.setText("");
        txtHospId.setText("");
        txtHouseName.setText("");
        txtCommId.setText("");
        txtPwd.setText("");
        
        

       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCommId;
    private javax.swing.JLabel lblHospId;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtCommId;
    private javax.swing.JTextField txtHospId;
    private javax.swing.JTextField txtHouseName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPwd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
