/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.DataService;
import model.HospitalAdmin;
import model.Patient;

/**
 *
 * @author madhav
 */
public class LoginPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPatientPanel
     */
    
    DataService HAdmin;
    Patient p;
    public LoginPatientPanel(DataService HAdmin) {
        initComponents();
        this.HAdmin = HAdmin;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        splitPaneHALogin = new javax.swing.JSplitPane();
        controlPanelHALogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbHAUsername = new javax.swing.JLabel();
        txtPUsername = new javax.swing.JTextField();
        lbHAPassword = new javax.swing.JLabel();
        txtPPassword = new javax.swing.JTextField();
        btnHALogin = new javax.swing.JButton();
        workAreaHALogin = new javax.swing.JPanel();

        jLabel1.setText("Enter Patient Login Details ");

        lbHAUsername.setText(" Username:");

        txtPUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPUsernameActionPerformed(evt);
            }
        });

        lbHAPassword.setText("Password:");

        btnHALogin.setText("Login ");
        btnHALogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHALoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelHALoginLayout = new javax.swing.GroupLayout(controlPanelHALogin);
        controlPanelHALogin.setLayout(controlPanelHALoginLayout);
        controlPanelHALoginLayout.setHorizontalGroup(
            controlPanelHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelHALoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(controlPanelHALoginLayout.createSequentialGroup()
                .addGroup(controlPanelHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelHALoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanelHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelHALoginLayout.createSequentialGroup()
                                .addComponent(lbHAUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelHALoginLayout.createSequentialGroup()
                                .addComponent(lbHAPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPPassword))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelHALoginLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnHALogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelHALoginLayout.setVerticalGroup(
            controlPanelHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHALoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHAUsername)
                    .addComponent(txtPUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHAPassword)
                    .addComponent(txtPPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHALogin)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        splitPaneHALogin.setLeftComponent(controlPanelHALogin);

        javax.swing.GroupLayout workAreaHALoginLayout = new javax.swing.GroupLayout(workAreaHALogin);
        workAreaHALogin.setLayout(workAreaHALoginLayout);
        workAreaHALoginLayout.setHorizontalGroup(
            workAreaHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        workAreaHALoginLayout.setVerticalGroup(
            workAreaHALoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        splitPaneHALogin.setRightComponent(workAreaHALogin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneHALogin)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(splitPaneHALogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPUsernameActionPerformed
 Patient searchPatient(String username,String password) {
        for(Patient e:this.HAdmin.getPatient()) {
            if(e.getUserName().matches(username) && e.getPwd().matches(password)) {
                return e;
            }
            
        }
        return null;
    }
    private void btnHALoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHALoginActionPerformed
        // TODO add your handling code here:
        String pUsername = txtPUsername.getText();
        String pPassword = txtPPassword.getText();
        Patient hap = this.searchPatient(pUsername,pPassword);
        this.p = hap;
//        Patient hap = this.searchPatient(haPassword);
        if(hap==null) {

           JOptionPane.showMessageDialog(this, "Patient ID does not exist! Please give valid Patient Id.");return;
        }else{
          FunctionPatJPanel fhaPanel = new FunctionPatJPanel(this.p,HAdmin);
          splitPaneHALogin.setRightComponent(fhaPanel);
            }
    }//GEN-LAST:event_btnHALoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHALogin;
    private javax.swing.JPanel controlPanelHALogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbHAPassword;
    private javax.swing.JLabel lbHAUsername;
    private javax.swing.JSplitPane splitPaneHALogin;
    private javax.swing.JTextField txtPPassword;
    private javax.swing.JTextField txtPUsername;
    private javax.swing.JPanel workAreaHALogin;
    // End of variables declaration//GEN-END:variables
}
