/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Services.LoginService;
import database.DoctorService;
import database.ForecastOrgAdminService;
import database.HospitalAdminService;
import database.LabAdminService;
import database.ManufacturerService;
import database.PatientService;
import database.PharmaceuticalAdminService;
import database.PharmacyAdminService;
import database.PlanningAdminService;
import database.ReporterService;
import database.RevenueAdminService;
import database.SystemAdminService;
import javax.swing.JOptionPane;
import model.Doctor;
import model.ForecastOrgAdmin;
import model.HospitalAdmin;
import model.LabAdmin;
import model.Manufacturer;
import model.Patient;
import model.Person;
import model.PharmaceuticalAdmin;
import model.PharmacyAdmin;
import model.PlanningAdmin;
import model.Reporter;
import model.RevenueAdmin;
import model.SystemAdmin;
import ui.doctor.DoctorPanel;
import ui.forecasting.ForecastOrgAdminPanel;
import ui.forecasting.PlanningAdminPanel;
import ui.hospital.HospitalAdminPanel;
import ui.laboratory.LabAdminPanel;
import ui.patient.PatientPanel;
import ui.manufacturer.ManufacturerPanel;
import ui.pharmaceutical.PharmaceuticalAdminPanel;
import ui.pharmacy.PharmacyAdminPanel;
import ui.revenue.ReporterPanel;
import ui.revenue.RevenueAdminPanel;
import ui.systsemadmin.SystemAdminPanel;
/**
 *
 * @author maheshsai
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.splitPanel.setRightComponent(null);
    }
    String userId;
    String userType;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        controlLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        newuserLabel = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(204, 204, 255));

        controlLabel.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        controlLabel.setForeground(new java.awt.Color(0, 0, 0));
        controlLabel.setText("Login");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        newuserLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newuserLabel.setForeground(new java.awt.Color(0, 0, 0));
        newuserLabel.setText("New User");

        btnRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 0, 0));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogout.setForeground(new java.awt.Color(255, 51, 51));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/logout.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/ppic.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/key.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(newuserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(controlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 44, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                .addComponent(btnLogout)
                                .addGap(36, 36, 36)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField1, usernameField});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnLogout)
                .addGap(29, 29, 29)
                .addComponent(controlLabel)
                .addGap(76, 76, 76)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(newuserLabel)
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jPasswordField1});

        splitPanel.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = this.usernameField.getText();
        String password = this.jPasswordField1.getText();
        LoginService registrationService = new LoginService();

        Person res = registrationService.validate(username, password);
        if(res == null) {
            
            JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
            return;
        }
        if(!res.password.equals(password)) {
            JOptionPane.showMessageDialog(this, "Failure: Password doesn't match");
            return;
        }
        this.userId = res.getId();
        this.userType = res.getRole();
        this.btnLogin.setEnabled(false);
        this.btnRegister.setEnabled(false);
        this.btnLogout.setEnabled(true);
        if(this.userType.equals("Patient")) {
            PatientService p = new PatientService();
            Patient patient = p.getPatient(this.userId);
            if(patient == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            System.out.println(patient.getName()+"patient");
            this.usernameField.setText(patient.getName());
            this.jPasswordField1.setText("");
            PatientPanel pl = new PatientPanel(patient, this.splitPanel);
            this.splitPanel.setRightComponent(pl);

        } else if(this.userType.equals("Doctor")) {
            DoctorService ds = new DoctorService();
            Doctor doc = ds.getDoctor(userId);
            if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            DoctorPanel docpanel = new DoctorPanel(doc,this.splitPanel);
            System.out.println(doc);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Manufacturer")) {
            ManufacturerService ds = new ManufacturerService();
            System.out.println(userId);
            Manufacturer doc = ds.getManufacturer(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            ManufacturerPanel docpanel = new ManufacturerPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Pharmacy Admin")) {
            PharmacyAdminService ds = new PharmacyAdminService();
            PharmacyAdmin doc = ds.getPhrmacyAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            System.out.println(doc.getName()+doc.getId());
            PharmacyAdminPanel docpanel = new PharmacyAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Planning Admin")) {
            PlanningAdminService ds = new PlanningAdminService();
            PlanningAdmin doc = ds.getPlanningAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            PlanningAdminPanel docpanel = new PlanningAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Revenue Admin")) {
            RevenueAdminService ds = new RevenueAdminService();
            RevenueAdmin doc = ds.getRevenueAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            System.out.println(doc);
            System.out.println(userId);
            RevenueAdminPanel docpanel = new RevenueAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Hospital Admin")) {
            HospitalAdminService ds = new HospitalAdminService();
            HospitalAdmin doc = ds.getHospitalAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            System.out.println(doc);
            HospitalAdminPanel docpanel = new HospitalAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Reporter")) {
            ReporterService ds = new ReporterService();
            Reporter doc = ds.getReporter(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            ReporterPanel docpanel = new ReporterPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Forecast Org Admin")) {
            ForecastOrgAdminService ds = new ForecastOrgAdminService();
            ForecastOrgAdmin doc = ds.getForecastOrgAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            ForecastOrgAdminPanel docpanel = new ForecastOrgAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("LabAdmin")) {
            LabAdminService ds = new LabAdminService();
            LabAdmin doc = ds.getLabAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            LabAdminPanel docpanel = new LabAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("Pharmaceutical Admin")) {
            PharmaceuticalAdminService ds = new PharmaceuticalAdminService();
            PharmaceuticalAdmin doc = ds.getPharmaceuticalAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            PharmaceuticalAdminPanel docpanel = new PharmaceuticalAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        } else if(this.userType.equals("System Admin")) {
            SystemAdminService ds = new SystemAdminService();
            SystemAdmin doc = ds.getSystemAdmin(userId);
             if(doc == null ) {
                 JOptionPane.showMessageDialog(this, "Failure: User doesn't exist");
                return;
            }
            SystemAdminPanel docpanel = new SystemAdminPanel(doc,this.splitPanel);
            this.usernameField.setText(doc.getName());
            this.jPasswordField1.setText("");
            this.splitPanel.setRightComponent(docpanel);
        }
//        else if(this.userType.equals("Lab Admin")) {
//            LabAdminService ls = new LabAdminService();
//            LabAdmin admin = ls.getLabAdmin(userId);
//            this.usernameField.setText(admin.getName());
//            this.passwordField.setText("");
//            LabAdminPanel panel = new LabAdminPanel(admin,this.splitPanel);
//            this.splitPanel.setRightComponent(panel);
//        } else if(this.userType.equals("Hospital Admin")) {
//            HospitalAdminService ls = new HospitalAdminService();
//            HospitalAdmin admin = ls.getHospitalAdmin(userId);
//            this.usernameField.setText(admin.getName());
//            this.passwordField.setText("");
//            HospitalAdminPanel panel = new HospitalAdminPanel(admin,this.splitPanel);
//            this.splitPanel.setRightComponent(panel);
//        } else if(this.userType.equals("Community Admin")) {
//            CommunityAdminService ls = new CommunityAdminService();
//            CommunityAdmin admin = ls.getCommunityAdmin(userId);
//            this.usernameField.setText(admin.getName());
//            this.passwordField.setText("");
//            CommunityAdminPanel panel = new CommunityAdminPanel(admin,this.splitPanel);
//            this.splitPanel.setRightComponent(panel);
//        } else if(this.userType.equals("System Admin")) {
//            SystemAdminService ls = new SystemAdminService();
//            SystemAdmin admin = ls.getSystemAdmin(userId);
//            this.usernameField.setText(admin.getName());
//            this.passwordField.setText("");
//            SystemAdminPanel panel = new SystemAdminPanel(admin,this.splitPanel);
//            this.splitPanel.setRightComponent(panel);
//        }
        System.out.println(this.userId+this.userType);

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        //        this.splitPanel.setLeftComponent(null);
        this.btnLogin.setEnabled(false);

        RegisterPanel registerPanel = new RegisterPanel(this.splitPanel, this.btnLogin);
        this.splitPanel.setRightComponent(registerPanel);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.splitPanel.setRightComponent(null);
        this.userId = null;
        this.userType = null;
        this.btnLogin.setEnabled(true);
        this.btnLogout.setEnabled(false);
        this.btnRegister.setEnabled(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel controlLabel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel newuserLabel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
