/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Services.LoginService;
import Services.MediaService;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Person;

/**
 *
 * @author maheshsai
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    JSplitPane mainPanel;
    JButton btnLogin;
    BufferedImage img;
    public RegisterPanel(JSplitPane panel, JButton btnLogin) {
        initComponents();
        this.mainPanel = panel;
        this.btnLogin = btnLogin;
        this.rdbtnPatient.setActionCommand("Patient");
        this.rdbtnDoctor.setActionCommand("Doctor");
        this.rdbtnSystemAdmin.setActionCommand("System Admin");
        this.rdbtnHospitalAdmin.setActionCommand("Hospital Admin");
        this.rdbtnManufacturer.setActionCommand("Manufacturer");
        this.rdbtnLabAdmin.setActionCommand("LabAdmin");
        this.rdbtnPharmacyAdmin.setActionCommand("Pharmacy Admin");
        this.rdbtnPlanningAdmin.setActionCommand("Planning Admin");
        this.rdbtnRevenueAdmin.setActionCommand("Revenue Admin");
        this.rdbtnReporter.setActionCommand("Reporter");
        this.rdbtnForecaster.setActionCommand("Forecast Org Admin");
        this.rdbtnPharmaceuticalAdmin.setActionCommand("Pharmaceutical Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupUserType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rdbtnPatient = new javax.swing.JRadioButton();
        rdbtnDoctor = new javax.swing.JRadioButton();
        rdbtnSystemAdmin = new javax.swing.JRadioButton();
        rdbtnHospitalAdmin = new javax.swing.JRadioButton();
        rdbtnManufacturer = new javax.swing.JRadioButton();
        rdbtnLabAdmin = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        rdbtnPharmacyAdmin = new javax.swing.JRadioButton();
        rdbtnPlanningAdmin = new javax.swing.JRadioButton();
        rdbtnRevenueAdmin = new javax.swing.JRadioButton();
        rdbtnReporter = new javax.swing.JRadioButton();
        rdbtnForecaster = new javax.swing.JRadioButton();
        rdbtnPharmaceuticalAdmin = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register User");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("User Name");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Type");

        btnGroupUserType.add(rdbtnPatient);
        rdbtnPatient.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnPatient.setText("Patient");

        btnGroupUserType.add(rdbtnDoctor);
        rdbtnDoctor.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnDoctor.setText("Doctor");
        rdbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDoctorActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnSystemAdmin);
        rdbtnSystemAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnSystemAdmin.setText("System Admin");
        rdbtnSystemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSystemAdminActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnHospitalAdmin);
        rdbtnHospitalAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnHospitalAdmin.setText("Hospital Admin");
        rdbtnHospitalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnHospitalAdminActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnManufacturer);
        rdbtnManufacturer.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnManufacturer.setText("Manufacturer");
        rdbtnManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnManufacturerActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnLabAdmin);
        rdbtnLabAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnLabAdmin.setText("Lab Admin");
        rdbtnLabAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnLabAdminActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnPharmacyAdmin);
        rdbtnPharmacyAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnPharmacyAdmin.setText("Pharmacy Admin");
        rdbtnPharmacyAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPharmacyAdminActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnPlanningAdmin);
        rdbtnPlanningAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnPlanningAdmin.setText("Planning Admin");
        rdbtnPlanningAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPlanningAdminActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnRevenueAdmin);
        rdbtnRevenueAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnRevenueAdmin.setText("Revenue Admin");
        rdbtnRevenueAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnRevenueAdminActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnReporter);
        rdbtnReporter.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnReporter.setText("Reporter");
        rdbtnReporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnReporterActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnForecaster);
        rdbtnForecaster.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnForecaster.setText("Forecaster");
        rdbtnForecaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnForecasterActionPerformed(evt);
            }
        });

        btnGroupUserType.add(rdbtnPharmaceuticalAdmin);
        rdbtnPharmaceuticalAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnPharmaceuticalAdmin.setText("Pharmaceutical Admin");
        rdbtnPharmaceuticalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPharmaceuticalAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 324, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbtnPatient)
                                    .addComponent(rdbtnManufacturer)
                                    .addComponent(rdbtnRevenueAdmin)
                                    .addComponent(rdbtnForecaster)
                                    .addComponent(rdbtnHospitalAdmin))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbtnDoctor)
                                    .addComponent(rdbtnPharmaceuticalAdmin)
                                    .addComponent(rdbtnReporter)
                                    .addComponent(rdbtnPlanningAdmin)
                                    .addComponent(jLabel5))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbtnLabAdmin)
                            .addComponent(rdbtnPharmacyAdmin)
                            .addComponent(rdbtnSystemAdmin))))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nameField, passwordField, usernameField});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnPatient)
                    .addComponent(rdbtnDoctor)
                    .addComponent(rdbtnLabAdmin))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnManufacturer)
                    .addComponent(rdbtnPharmaceuticalAdmin)
                    .addComponent(rdbtnPharmacyAdmin))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnRevenueAdmin)
                    .addComponent(rdbtnReporter)
                    .addComponent(rdbtnSystemAdmin))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnForecaster)
                    .addComponent(rdbtnPlanningAdmin))
                .addGap(32, 32, 32)
                .addComponent(rdbtnHospitalAdmin)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(132, 132, 132))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nameField, passwordField, usernameField});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed
private static boolean checkString(String str) {
    char ch;
    boolean capitalFlag = false;
    boolean lowerCaseFlag = false;
    boolean numberFlag = false;
    for(int i=0;i < str.length();i++) {
        ch = str.charAt(i);
        if( Character.isDigit(ch)) {
            numberFlag = true;
        }
        else if (Character.isUpperCase(ch)) {
            capitalFlag = true;
        } else if (Character.isLowerCase(ch)) {
            lowerCaseFlag = true;
        }
        if(numberFlag && capitalFlag && lowerCaseFlag)
            return true;
    }
    return false;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginService registrationService = new LoginService();
        String name = this.nameField.getText();
        String username = this.usernameField.getText();
        String password = this.passwordField.getText();
        if(name.length()<=0) {
            JOptionPane.showMessageDialog(this, "Name is not valid");
            return;
        }
        if(username.length()<=6) {
            JOptionPane.showMessageDialog(this, "Username is not valid");
            return;
        }

        if((password == null) || (password.length()<=8) || !(this.checkString(password))) {
            System.out.println(checkString(password));
            JOptionPane.showMessageDialog(this, "Password is not valid");
            return;
        }
        if(this.btnGroupUserType.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "User type is not valid");
            return;
        }
        String type = this.btnGroupUserType.getSelection().getActionCommand();
        System.out.println(this.btnGroupUserType.getSelection());

        if(type.length() <=0) {
            JOptionPane.showMessageDialog(this, "User type is not valid");
            return;
        }
        Person p = new Person(name,password,username,type);
        System.out.println(p.getId());
        String message = registrationService.register(p);
        
        if(img != null) {
            new MediaService().saveImage(img, p.getId());
        }
        
        JOptionPane.showMessageDialog(this, message);
        if(message.contains("success")) {
            this.passwordField.setText("");
            this.usernameField.setText("");
            this.nameField.setText("");
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdbtnLabAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnLabAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnLabAdminActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.mainPanel.setRightComponent(null);
        this.btnLogin.setEnabled(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void rdbtnManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnManufacturerActionPerformed

    private void rdbtnHospitalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnHospitalAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnHospitalAdminActionPerformed

    private void rdbtnPharmacyAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPharmacyAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnPharmacyAdminActionPerformed

    private void rdbtnPlanningAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPlanningAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnPlanningAdminActionPerformed

    private void rdbtnRevenueAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnRevenueAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnRevenueAdminActionPerformed

    private void rdbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnDoctorActionPerformed

    private void rdbtnReporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnReporterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnReporterActionPerformed

    private void rdbtnForecasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnForecasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnForecasterActionPerformed

    private void rdbtnPharmaceuticalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPharmaceuticalAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnPharmaceuticalAdminActionPerformed

    private void rdbtnSystemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSystemAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnSystemAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btnGroupUserType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JRadioButton rdbtnDoctor;
    private javax.swing.JRadioButton rdbtnForecaster;
    private javax.swing.JRadioButton rdbtnHospitalAdmin;
    private javax.swing.JRadioButton rdbtnLabAdmin;
    private javax.swing.JRadioButton rdbtnManufacturer;
    private javax.swing.JRadioButton rdbtnPatient;
    private javax.swing.JRadioButton rdbtnPharmaceuticalAdmin;
    private javax.swing.JRadioButton rdbtnPharmacyAdmin;
    private javax.swing.JRadioButton rdbtnPlanningAdmin;
    private javax.swing.JRadioButton rdbtnReporter;
    private javax.swing.JRadioButton rdbtnRevenueAdmin;
    private javax.swing.JRadioButton rdbtnSystemAdmin;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
