/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import Services.MailService;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JSplitPane;
import model.Patient;
import ui.encounter.AddVitalSignPanel;
import ui.encounter.CreateEncounterPanel;
import ui.encounter.CreateEncounterPatientPanel;
import ui.encounter.PatientEncounterHistoryPanel;
import ui.encounter.PatientVitalSignsHistoryPanel;
import ui.event.PersonParticipationListPanel;
import ui.hospital.HospitalListPanel;
import ui.revenue.RevenueListOfHospitalsPanel;
import ui.event.RegisterEventPanel;

/**
 *
 * @author maheshsai
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    JSplitPane mainPanel;
    ArrayList<Component> al;
    Patient user;
    public PatientPanel(Patient user, JSplitPane mainPanel) {
        initComponents();
        this.user = user;
        this.mainPanel = mainPanel;
        this.al = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpdateAddress = new javax.swing.JButton();
        btnViewHistory = new javax.swing.JButton();
        btnSearchDocs = new javax.swing.JButton();
        btnVitalSignsHistory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuyMedicine = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnBuyMedicine1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Patient Details");

        btnUpdateAddress.setForeground(new java.awt.Color(255, 102, 153));
        btnUpdateAddress.setText("Update Address");
        btnUpdateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAddressActionPerformed(evt);
            }
        });

        btnViewHistory.setForeground(new java.awt.Color(0, 0, 0));
        btnViewHistory.setText("View Encounter History");
        btnViewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHistoryActionPerformed(evt);
            }
        });

        btnSearchDocs.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchDocs.setText("Nearby Hospitals");
        btnSearchDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDocsActionPerformed(evt);
            }
        });

        btnVitalSignsHistory.setForeground(new java.awt.Color(0, 0, 0));
        btnVitalSignsHistory.setText("View Vital Sign History");
        btnVitalSignsHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalSignsHistoryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Address");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Search Hospitals and Medicine ");

        btnBuyMedicine.setForeground(new java.awt.Color(0, 0, 0));
        btnBuyMedicine.setText("Buy Medicine");
        btnBuyMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyMedicineActionPerformed(evt);
            }
        });

        jButton3.setText("Register Event");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnBuyMedicine1.setForeground(new java.awt.Color(0, 0, 0));
        btnBuyMedicine1.setText("Create Encounter");
        btnBuyMedicine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyMedicine1ActionPerformed(evt);
            }
        });

        jButton4.setText("View Events");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Encounters and Vital Signs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(64, 64, 64)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuyMedicine1)
                                    .addComponent(btnVitalSignsHistory))
                                .addGap(80, 80, 80)
                                .addComponent(btnViewHistory)))))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuyMedicine)
                .addGap(234, 234, 234))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUpdateAddress)
                        .addComponent(jLabel2)
                        .addComponent(btnSearchDocs))
                    .addContainerGap(438, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuyMedicine, btnBuyMedicine1, btnSearchDocs, btnViewHistory, btnVitalSignsHistory, jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnBuyMedicine)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVitalSignsHistory)
                    .addComponent(btnViewHistory))
                .addGap(28, 28, 28)
                .addComponent(btnBuyMedicine1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(118, 118, 118))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(btnUpdateAddress)
                    .addGap(61, 61, 61)
                    .addComponent(btnSearchDocs)
                    .addContainerGap(336, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuyMedicine, btnBuyMedicine1, btnSearchDocs, btnViewHistory, btnVitalSignsHistory, jButton3, jButton4});

    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAddressActionPerformed
        // TODO add your handling code here:
        this.al.add(this);
        UpdateAddressPanel upanel = new UpdateAddressPanel(this.user, this.mainPanel,this.al);
        this.mainPanel.setRightComponent(upanel);
    }//GEN-LAST:event_btnUpdateAddressActionPerformed

    private void btnViewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHistoryActionPerformed
        // TODO add your handling code here:
        PatientEncounterHistoryPanel ehp = new PatientEncounterHistoryPanel(this.user,this.mainPanel,this.al);
        this.al.add(this);
        this.mainPanel.setRightComponent(ehp);
    }//GEN-LAST:event_btnViewHistoryActionPerformed

    private void btnSearchDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDocsActionPerformed
        // TODO add your handling code here:
//        NearbyDoctorsPanel ndp = new NearbyDoctorsPanel(this.user,this.mainPanel,this.al);
//        new MailService().actionPerformed("test","test","maheshsai252@gmail.com","maheshsai252@gmail.com");
        NearbyHospitalListPanel panel = new NearbyHospitalListPanel(this.mainPanel, this.al);
        this.al.add(this);
        this.mainPanel.setRightComponent(panel);
    }//GEN-LAST:event_btnSearchDocsActionPerformed

    private void btnVitalSignsHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalSignsHistoryActionPerformed
        // TODO add your handling code here:\
        PatientVitalSignsHistoryPanel panel = new PatientVitalSignsHistoryPanel(this.user,this.mainPanel, this.al);
        this.al.add(this);
        this.mainPanel.setRightComponent(panel);
    }//GEN-LAST:event_btnVitalSignsHistoryActionPerformed

    private void btnBuyMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyMedicineActionPerformed
        // TODO add your handling code here:
        PharmacyListPanel panel = new PharmacyListPanel(user, this.mainPanel, this.al);
        this.al.add(this);
        this.mainPanel.setRightComponent(panel);
    }//GEN-LAST:event_btnBuyMedicineActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        RegisterEventPanel panel;
        panel = new RegisterEventPanel(this.user.getId(), this.mainPanel,this.al);
        this.al.add(this);
        this.mainPanel.setRightComponent(panel);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBuyMedicine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyMedicine1ActionPerformed
        // TODO add your handling code here:
        CreateEncounterPatientPanel panel = new CreateEncounterPatientPanel(user, this.mainPanel, this.al);
        this.al.add(this);
        this.mainPanel.setRightComponent(panel);
    }//GEN-LAST:event_btnBuyMedicine1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        PersonParticipationListPanel panel = new PersonParticipationListPanel(user, this.mainPanel, this.al);
        this.al.add(this);
        this.mainPanel.setRightComponent(panel);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyMedicine;
    private javax.swing.JButton btnBuyMedicine1;
    private javax.swing.JButton btnSearchDocs;
    private javax.swing.JButton btnUpdateAddress;
    private javax.swing.JButton btnViewHistory;
    private javax.swing.JButton btnVitalSignsHistory;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
