/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.encounter;

import database.EncounterService;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.Encounter;

/**
 *
 * @author somes
 */
public class DoctorEncounterHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorEncounterHistoryPanel
     */
    JSplitPane mainPanel;
    ArrayList<Component> al;
    EncounterService ehs;
    Doctor d;
    public DoctorEncounterHistoryPanel(Doctor user, JSplitPane mainPanel, ArrayList<Component> al) {
        initComponents();
        ehs = new EncounterService();
        this.mainPanel = mainPanel;
        this.d = user;
        this.al = al;
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();
        model.setRowCount(0);
        ArrayList<Encounter> encounters = this.ehs.getAllEncountersOfDoctor(user.getId());
        for(Encounter encounter: encounters) {
                Object[] row = new Object[3];
                row[0] = encounter.getPatient().getName();
                row[1] = encounter;
                row[2] = encounter.getEncounteredTime().toString();
                model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounters = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblRespiratoryRate = new javax.swing.JLabel();
        btnLeave = new javax.swing.JButton();
        btnDiagnose = new javax.swing.JButton();
        lblWeight = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiagnose = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblBP1 = new javax.swing.JLabel();
        lblage1 = new javax.swing.JLabel();
        lblHeartRate1 = new javax.swing.JLabel();
        lblRespiratoryRate1 = new javax.swing.JLabel();
        lblWeight1 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Encounter");

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient", "Doctor", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblEncounters);

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jButton1.setText("View Vital Signs ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selected Vital Signs");

        lblBP.setText("Blood Pressure");

        lblage.setText("Age");

        lblHeartRate.setText("Heart Rate");

        lblRespiratoryRate.setText("Respiratory Rate");

        btnLeave.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnLeave.setForeground(new java.awt.Color(255, 0, 0));
        btnLeave.setText("Leave Encounter");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        btnDiagnose.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnDiagnose.setForeground(new java.awt.Color(204, 0, 255));
        btnDiagnose.setText("Diagnose");
        btnDiagnose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnoseActionPerformed(evt);
            }
        });

        lblWeight.setText("Weight");

        txtDiagnose.setColumns(20);
        txtDiagnose.setRows(5);
        jScrollPane2.setViewportView(txtDiagnose);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Diagnose");

        lblBP1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblBP1.setForeground(new java.awt.Color(0, 0, 0));
        lblBP1.setText("Blood Pressure");

        lblage1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblage1.setForeground(new java.awt.Color(0, 0, 0));
        lblage1.setText("Age");

        lblHeartRate1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblHeartRate1.setForeground(new java.awt.Color(0, 0, 0));
        lblHeartRate1.setText("Heart Rate");

        lblRespiratoryRate1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblRespiratoryRate1.setForeground(new java.awt.Color(0, 0, 0));
        lblRespiratoryRate1.setText("Respiratory Rate");

        lblWeight1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblWeight1.setForeground(new java.awt.Color(0, 0, 0));
        lblWeight1.setText("Weight");

        lblType.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblType.setForeground(new java.awt.Color(0, 0, 0));
        lblType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblType.setText("Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLeave)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBP1)
                            .addComponent(lblHeartRate1)
                            .addComponent(lblWeight1)
                            .addComponent(lblRespiratoryRate1)
                            .addComponent(lblage1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWeight)
                            .addComponent(lblBP)
                            .addComponent(lblage)
                            .addComponent(lblHeartRate)
                            .addComponent(lblRespiratoryRate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDiagnose, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBP1, lblHeartRate1, lblRespiratoryRate1, lblWeight1, lblage1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBP, lblHeartRate, lblRespiratoryRate, lblWeight, lblage});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblBP1)
                        .addGap(18, 18, 18)
                        .addComponent(lblHeartRate1)
                        .addGap(53, 53, 53)
                        .addComponent(lblWeight1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(lblType)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblage)
                            .addComponent(lblage1))
                        .addGap(18, 18, 18)
                        .addComponent(lblBP)
                        .addGap(18, 18, 18)
                        .addComponent(lblHeartRate)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRespiratoryRate)
                            .addComponent(lblRespiratoryRate1))
                        .addGap(18, 18, 18)
                        .addComponent(lblWeight))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeave)
                    .addComponent(btnDiagnose))
                .addGap(14, 14, 14))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBP1, lblHeartRate1, lblRespiratoryRate1, lblWeight1, lblage1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBP, lblHeartRate, lblRespiratoryRate, lblWeight, lblage});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Component c = this.al.get(this.al.size()-1);
        this.al.remove(this.al.size()-1);
        this.mainPanel.setRightComponent(c);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int idx = this.tblEncounters.getSelectedRow();
        if(idx<0) {
            JOptionPane.showMessageDialog(this, "Not correct index");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();

        Encounter v = (Encounter) model.getValueAt(idx, 1);
        if(v.getVitalSigns() == null) {
            JOptionPane.showMessageDialog(this, "Not correct vital signs");
            return;
        }

        this.lblage.setText(String.valueOf(v.getVitalSigns().getAgeGroup()));
        this.lblBP.setText(String.valueOf(v.getVitalSigns().getBloodPressure()));
        this.lblHeartRate.setText(String.valueOf(v.getVitalSigns().getHeartRate()));
        this.lblRespiratoryRate.setText(String.valueOf(v.getVitalSigns().getRespiratoryRate()));
        this.lblWeight.setText(String.valueOf(v.getVitalSigns().getWeightInKgs()));
        this.lblType.setText(v.getType());
//        PatientService ps = new PatientService();

        if(!v.getDiagnosis().equals("NA")) {
            this.txtDiagnose.setText(v.getDiagnosis());
        } else {
//            if(ps.isPatientNormal(v.getVitalSigns())){
                this.txtDiagnose.setText("Patient is normal and continue a good diet");
//            } else {
//                this.txtDiagnose.setText("Patient is not normal and have a good diet");
//            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
        int idx = this.tblEncounters.getSelectedRow();
        if(idx<0) {
            JOptionPane.showMessageDialog(this, "Not correct index");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();

        Encounter v = (Encounter) model.getValueAt(idx, 1);

        v.setDoctorId(null);
        v.setDoctor(null);

        this.ehs.update(v);
        model.setRowCount(0);
        ArrayList<Encounter> encounters = this.ehs.getAllEncountersOfDoctor(this.d.getId());
        for(Encounter encounter: encounters) {
            Object[] row = new Object[3];
            row[0] = encounter.getPatient().getName();
            row[1] = encounter;
            row[2] = encounter.getEncounteredTime();
            model.addRow(row);
        }
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void btnDiagnoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnoseActionPerformed
        // TODO add your handling code here:
        int idx = this.tblEncounters.getSelectedRow();
        if(idx<0) {
            JOptionPane.showMessageDialog(this, "Not correct index");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) this.tblEncounters.getModel();

        Encounter v = (Encounter) model.getValueAt(idx, 1);
        if(v.getVitalSigns() == null) {
            JOptionPane.showMessageDialog(this, "Not correct vital signs");
            return;
        }
        if(this.txtDiagnose.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "Diagnose info is empty");
            return;
        }
        String diagnosis = this.txtDiagnose.getText();
        diagnosis = diagnosis.replace(",", " ").replace("\n", " ");
        v.setDiagnosis(diagnosis);
        this.ehs.update(v);
        JOptionPane.showMessageDialog(this, "Diagnose updated");
    }//GEN-LAST:event_btnDiagnoseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDiagnose;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblBP1;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblHeartRate1;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblRespiratoryRate1;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeight1;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblage1;
    private javax.swing.JTable tblEncounters;
    private javax.swing.JTextArea txtDiagnose;
    // End of variables declaration//GEN-END:variables
}
